Parameters:
  VPCName:
    Description: The name of the VPC
    Type: String
    Default: lab-6-3
  EnvironmentName:
    Description: lab-6-3
    Type: String
    Default: lab-6-3
  BucketName:
    Description: lab-6-3
    Type: String
    Default: lab-6-3
Mappings:
  SubnetConfig:
    VPC:
      CIDR: 10.20.0.0/16
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock:
        'Fn::FindInMap':
          - SubnetConfig
          - VPC
          - CIDR
      Tags:
        - Key: Name
          Value: lab-6-3
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId:
        Ref: VPC
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: lab-6-3